import { Transaction } from "./recentTransactions";

export const transactions: Transaction[] = [
  {
    id: 1,
    name: {
      first: "John",
      last: "Doe",
      email: "john.doe@example.com",
      website: "http://johndoe.com",
      contact: "+1234567890",
    },
    total: 250.0,
    status: "Paid",
    method: "PayPal",
    date: "15 minutes ago",
  },
  {
    id: 2,
    name: {
      first: "Jane",
      last: "Smith",
      email: "jane.smith@example.com",
      website: "http://janesmith.com",
      contact: "+0987654321",
    },
    total: 75.5,
    status: "Pending",
    method: "Gpay",
    date: "1 hour ago",
  },
  {
    id: 3,
    name: {
      first: "Alice",
      last: "Johnson",
      email: "alice.johnson@example.com",
      website: "http://alicejohnson.com",
      contact: "+1122334455",
    },
    total: 120.0,
    status: "Paid",
    method: "Credit Card",
    date: "2 hours ago",
  },
  {
    id: 4,
    name: {
      first: "Bob",
      last: "Brown",
      email: "bob.brown@example.com",
      website: "http://bobbrown.com",
      contact: "+2233445566",
    },
    total: 45.75,
    status: "Pending",
    method: "PayPal",
    date: "3 hours ago",
  },
  {
    id: 5,
    name: {
      first: "Charlie",
      last: "Davis",
      email: "charlie.davis@example.com",
      website: "http://charliedavis.com",
      contact: "+3344556677",
    },
    total: 99.99,
    status: "Paid",
    method: "Gpay",
    date: "4 hours ago",
  },
  {
    id: 6,
    name: {
      first: "Eve",
      last: "Martin",
      email: "eve.martin@example.com",
      website: "http://evemartin.com",
      contact: "+4455667788",
    },
    total: 33.5,
    status: "Pending",
    method: "Credit Card",
    date: "5 hours ago",
  },
  {
    id: 7,
    name: {
      first: "Frank",
      last: "Garcia",
      email: "frank.garcia@example.com",
      website: "http://frankgarcia.com",
      contact: "+5566778899",
    },
    total: 210.0,
    status: "Paid",
    method: "PayPal",
    date: "6 hours ago",
  },
  {
    id: 8,
    name: {
      first: "Grace",
      last: "Wilson",
      email: "grace.wilson@example.com",
      website: "http://gracewilson.com",
      contact: "+6677889900",
    },
    total: 60.25,
    status: "Pending",
    method: "Gpay",
    date: "7 hours ago",
  },
  {
    id: 9,
    name: {
      first: "Hannah",
      last: "Anderson",
      email: "hannah.anderson@example.com",
      website: "http://hannahanderson.com",
      contact: "+7788990011",
    },
    total: 150.0,
    status: "Paid",
    method: "Credit Card",
    date: "8 hours ago",
  },
  {
    id: 10,
    name: {
      first: "Ivy",
      last: "Thomas",
      email: "ivy.thomas@example.com",
      website: "http://ivythomas.com",
      contact: "+8899001122",
    },
    total: 80.0,
    status: "Pending",
    method: "PayPal",
    date: "9 hours ago",
  },
  {
    id: 11,
    name: {
      first: "Jack",
      last: "Jackson",
      email: "jack.jackson@example.com",
      website: "http://jackjackson.com",
      contact: "+9900112233",
    },
    total: 200.0,
    status: "Paid",
    method: "Gpay",
    date: "10 hours ago",
  },
  {
    id: 12,
    name: {
      first: "Karen",
      last: "White",
      email: "karen.white@example.com",
      website: "http://karenwhite.com",
      contact: "+1011121314",
    },
    total: 55.25,
    status: "Pending",
    method: "Credit Card",
    date: "11 hours ago",
  },
  {
    id: 13,
    name: {
      first: "Leo",
      last: "Lopez",
      email: "leo.lopez@example.com",
      website: "http://leolopez.com",
      contact: "+1213141516",
    },
    total: 130.75,
    status: "Paid",
    method: "PayPal",
    date: "12 hours ago",
  },
  {
    id: 14,
    name: {
      first: "Mia",
      last: "Martinez",
      email: "mia.martinez@example.com",
      website: "http://miamartinez.com",
      contact: "+1314151617",
    },
    total: 45.0,
    status: "Pending",
    method: "Gpay",
    date: "13 hours ago",
  },
  {
    id: 15,
    name: {
      first: "Noah",
      last: "Harris",
      email: "noah.harris@example.com",
      website: "http://noahharris.com",
      contact: "+1415161718",
    },
    total: 90.0,
    status: "Paid",
    method: "Credit Card",
    date: "14 hours ago",
  },
];
