import type { GetServerSideProps, Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  currentRoute: string;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <div>Current Route</div>
      </body>
    </html>
  );
}
